"""
Agent 2 - Caseworker
Processes layoff posts, determines eligibility, fills forms, and drafts emails
"""
import os
import sys
import zipfile
import argparse
from datetime import datetime
from dotenv import load_dotenv
from tools.eligibility_engine import eligibility_engine_tool
from tools.drive_tool import drive_download_adk_tool
from tools.form_filler import form_filler_adk_tool, extract_info_from_post
from tools.gmail_tool import gmail_draft_adk_tool
from utils.shared_state import read_shared_state, append_to_shared_state

load_dotenv()


def create_email_body(name: str, programs: list, amount: float, state: str) -> str:
    """
    Creates an empathetic email body for the laid-off worker.
    
    Args:
        name: Worker's name
        programs: List of eligible programs
        amount: Total estimated benefit amount
        state: State abbreviation
    
    Returns:
        Email body text
    """
    program_names = {
        "UI": "Unemployment Insurance",
        "SNAP": "SNAP (Food Assistance)",
        "ACA": "ACA Health Insurance Subsidies",
        "RETRAINING": "Free Re-training Vouchers"
    }
    
    programs_text = "\n".join([f"• {program_names.get(p, p)}" for p in programs])
    
    body = f"""Hi {name},

I saw your post about being laid off, and I'm so sorry you're going through this difficult time. 

I wanted to let you know that you may qualify for several benefit programs that could help during this transition. Based on your location in {state}, you may be eligible for:

{programs_text}

The estimated total value of these benefits is approximately ${amount:,.2f}.

I've prepared your benefit application forms and attached them as a zip file. These forms are pre-filled with information I was able to gather, but please review and complete any missing sections before submitting.

**Next Steps:**
1. Review the attached forms
2. Complete any missing information
3. Submit to the appropriate state agencies
4. Keep copies for your records

**Important Notes:**
• These forms are auto-generated based on public information
• Please verify all information is accurate before submitting
• Each program has its own submission process - check the forms for details
• You can opt out of future communications by replying to this email

**Privacy:**
This email was generated by Second-Chance Agent, an open-source tool designed to help laid-off workers access benefits. No personal information is stored beyond what's necessary to generate these forms. Your privacy is important to us.

If you have questions about these benefits, please contact your state's benefits office directly.

Wishing you the best during this transition,

Second-Chance Agent
(Open-source project - MIT License)

---
To opt out of future communications, reply with "OPT OUT"
"""
    
    return body


def process_case(linkedin_url: str = None, entry: dict = None):
    """
    Processes a single case - determines eligibility, fills forms, drafts email.
    
    Args:
        linkedin_url: LinkedIn URL (optional if entry provided)
        entry: Entry dictionary from shared_state (optional)
    """
    # Get entry from shared_state if not provided
    if not entry:
        entries = read_shared_state()
        matching_entries = [e for e in entries if e.get("linkedin_url") == linkedin_url]
        if not matching_entries:
            print(f"[Caseworker] No entry found for {linkedin_url}")
            return
        entry = matching_entries[0]
    
    if entry.get("status") == "processed":
        print(f"[Caseworker] Entry already processed: {linkedin_url}")
        return
    
    print(f"[Caseworker] Processing case: {entry.get('linkedin_url')}")
    
    state = entry.get("state", "CA")
    post_text = entry.get("post_text", entry.get("summary", ""))
    linkedin_url = entry.get("linkedin_url")
    
    # Step 1: Determine eligibility
    print(f"[Caseworker] Determining eligibility for {state}...")
    eligibility_result = eligibility_engine_tool(state, post_text)
    programs = eligibility_result["programs"]
    amount = eligibility_result["amount"]
    
    print(f"[Caseworker] Eligible programs: {programs}")
    print(f"[Caseworker] Estimated amount: ${amount:,.2f}")
    
    # Step 2: Extract information from post
    print(f"[Caseworker] Extracting information from post...")
    info = extract_info_from_post(post_text, linkedin_url)
    
    # Step 3: Download PDFs from Google Drive
    print(f"[Caseworker] Downloading PDF forms for {state}...")
    drive_result = drive_download_adk_tool.func(
        folder_id=os.getenv("GOOGLE_DRIVE_FOLDER_ID", ""),
        state=state,
        output_dir=f"forms/{state}"
    )
    
    if drive_result["status"] != "success" or not drive_result.get("files"):
        print(f"[Caseworker] Warning: No PDFs downloaded. Using placeholder.")
        # Create a placeholder PDF directory structure
        os.makedirs(f"forms/{state}", exist_ok=True)
        pdf_files = []
    else:
        pdf_files = drive_result["files"]
    
    # Step 4: Fill PDF forms
    print(f"[Caseworker] Filling PDF forms...")
    filled_pdfs = []
    
    for pdf_path in pdf_files:
        output_path = pdf_path.replace(".pdf", "_filled.pdf")
        fill_result = form_filler_adk_tool.func(
            pdf_path=pdf_path,
            output_path=output_path,
            name=info["name"],
            address=info["address"],
            employer=info["last_employer"],
            wage=info["last_wage"],
            email=info.get("email"),
            phone=info.get("phone")
        )
        
        if fill_result["status"] == "success":
            filled_pdfs.append(output_path)
    
    # Step 5: Create zip file
    print(f"[Caseworker] Creating zip file...")
    zip_filename = f"benefits_{state}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.zip"
    zip_path = f"output/{zip_filename}"
    os.makedirs("output", exist_ok=True)
    
    with zipfile.ZipFile(zip_path, 'w') as zipf:
        for pdf_path in filled_pdfs:
            if os.path.exists(pdf_path):
                zipf.write(pdf_path, os.path.basename(pdf_path))
    
    print(f"[Caseworker] Created zip: {zip_path}")
    
    # Step 6: Draft email
    print(f"[Caseworker] Drafting email...")
    
    # Note: LinkedIn doesn't expose email addresses in public posts
    # In production, you would need to:
    # 1. Use LinkedIn API (requires authentication and may have restrictions)
    # 2. Extract from post content if mentioned
    # 3. Use a contact form or other method
    # For now, we'll use a placeholder - the email draft will be created
    # but the recipient email needs to be provided separately
    email_address = info.get("email") or entry.get("email") or "worker@example.com"
    
    if email_address == "worker@example.com":
        print(f"[Caseworker] Warning: No email address found. Using placeholder.")
        print(f"[Caseworker] In production, implement email extraction from LinkedIn profile or post.")
    
    email_body = create_email_body(
        name=info["name"],
        programs=programs,
        amount=amount,
        state=state
    )
    
    email_result = gmail_draft_adk_tool.func(
        to_email=email_address,
        subject="Your unemployment & benefit forms (auto-generated)",
        body=email_body,
        zip_file_path=zip_path if os.path.exists(zip_path) else None
    )
    
    if email_result["status"] == "success":
        print(f"[Caseworker] Email draft created: {email_result.get('draft_id')}")
    else:
        print(f"[Caseworker] Email draft error: {email_result.get('message')}")
    
    # Update shared state
    entry["status"] = "processed"
    entry["amount_unlocked"] = amount
    entry["programs"] = programs
    entry["processed_at"] = datetime.utcnow().isoformat()
    entry["zip_path"] = zip_path
    
    # Append updated entry (in production, would update in place)
    append_to_shared_state(entry)
    
    print(f"[Caseworker] Case processed successfully!")


def run_caseworker():
    """Main function to run Caseworker agent"""
    parser = argparse.ArgumentParser(description="Caseworker Agent - Process benefit applications")
    parser.add_argument("--url", help="LinkedIn URL to process")
    parser.add_argument("--all-pending", action="store_true", help="Process all pending entries")
    
    args = parser.parse_args()
    
    if args.url:
        process_case(linkedin_url=args.url)
    elif args.all_pending:
        entries = read_shared_state()
        pending = [e for e in entries if e.get("status") != "processed"]
        print(f"[Caseworker] Processing {len(pending)} pending entries...")
        for entry in pending:
            process_case(entry=entry)
    else:
        # Process most recent pending entry
        entries = read_shared_state()
        pending = [e for e in entries if e.get("status") != "processed"]
        if pending:
            process_case(entry=pending[-1])
        else:
            print("[Caseworker] No pending entries to process")


if __name__ == "__main__":
    run_caseworker()

